#!/bin/bash

killtree() {
    local _pid=$1
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_child} 
    done
    kill -9 ${_pid}
}

if [ $# -eq 0 -o $# -gt 1 ]; then
    echo "Usage: $(basename $0) <pid> [signal]"
    exit 1
fi

killtree $@